project1/config/routes.rb
Rails.application.routes.draw do
  resources :qas

end

project1/app/models/qa.rb
class Qa < ActiveRecord::Base
end

project1/app/controllers/qas_controller.rb
class QasController < ApplicationController
  before_action :set_qa, only: [:show, :edit, :update, :destroy]

  # GET /qas
  # GET /qas.json
  def index
    @qas = Qa.all
  end

  # GET /qas/1
  # GET /qas/1.json
  def show
  end

  # GET /qas/new
  def new
    @qa = Qa.new
  end

  # GET /qas/1/edit
  def edit
  end

  # POST /qas
  # POST /qas.json
  def create
    @qa = Qa.new(qa_params)

    respond_to do |format|
      if @qa.save
        format.html { redirect_to @qa, notice: 'Qa was successfully created.' }
        format.json { render :show, status: :created, location: @qa }
      else
        format.html { render :new }
        format.json { render json: @qa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qas/1
  # PATCH/PUT /qas/1.json
  def update
    respond_to do |format|
      if @qa.update(qa_params)
        format.html { redirect_to @qa, notice: 'Qa was successfully updated.' }
        format.json { render :show, status: :ok, location: @qa }
      else
        format.html { render :edit }
        format.json { render json: @qa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qas/1
  # DELETE /qas/1.json
  def destroy
    @qa.destroy
    respond_to do |format|
      format.html { redirect_to qas_url, notice: 'Qa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qa
      @qa = Qa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qa_params
      params.require(:qa).permit(:questions, :answer)
    end
end

project1/app/helpers/qas_helper.rb
module QasHelper
end

project1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

project1/app/views/qas/_form.html.erb
<%= form_for(@qa) do |f| %>
  <% if @qa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qa.errors.count, "error") %> prohibited this qa from being saved:</h2>

      <ul>
      <% @qa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :questions %><br>
    <%= f.text_area :questions %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project1/app/views/qas/edit.html.erb
<h1>Editing Qa</h1>

<%= render 'form' %>

<%= link_to 'Show', @qa %> |
<%= link_to 'Back', qas_path %>

project1/app/views/qas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Qas</h1>

<table>
  <thead>
    <tr>
      <th>Questions</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qas.each do |qa| %>
      <tr>
        <td><%= qa.questions %></td>
        <td><%= qa.answer %></td>
        <td><%= link_to 'Show', qa %></td>
        <td><%= link_to 'Edit', edit_qa_path(qa) %></td>
        <td><%= link_to 'Destroy', qa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qa', new_qa_path %>

project1/app/views/qas/new.html.erb
<h1>New Qa</h1>

<%= render 'form' %>

<%= link_to 'Back', qas_path %>

project1/app/views/qas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Questions:</strong>
  <%= @qa.questions %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @qa.answer %>
</p>

<%= link_to 'Edit', edit_qa_path(@qa) %> |
<%= link_to 'Back', qas_path %>